# Generated by Django 2.2.10 on 2020-02-27 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campusgo_teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campusgo_lectures', '0003_auto_20200227_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
            ],
            options={
                'verbose_name': 'Lecture Attendance',
                'verbose_name_plural': 'Lecture Attendances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campusgo_lectures.lectureschedule',),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(verbose_name='Date end')),
                ('name', models.CharField(max_length=512, verbose_name='Note')),
                ('note', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('PR', 'Present'), ('SC', 'Sick'), ('AB', 'Absent'), ('PE', 'Permit')], default='PR', max_length=3, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherattendance_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherattendance_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusgo_lectures.LectureSchedule', verbose_name='Schedule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusgo_teachers.Teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
                'unique_together': {('schedule', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('PR', 'Present'), ('SC', 'Sick'), ('AB', 'Absent'), ('PE', 'Permit')], default='PR', max_length=3, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentattendance_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentattendance_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusgo_lectures.LectureSchedule', verbose_name='Schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='campusgo_lectures.LectureStudent', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendances',
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
