# Generated by Django 2.2.10 on 2020-02-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusgo_core', '0002_auto_20200227_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusgosetting',
            options={'verbose_name': 'General', 'verbose_name_plural': 'General'},
        ),
    ]
