# Generated by Django 2.2.10 on 2020-02-28 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import modelcluster.fields
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campusgo_academic', '0002_auto_20200227_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('title', models.CharField(max_length=512, verbose_name='Name')),
                ('description', wagtail.core.fields.RichTextField(max_length=10000, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('program_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusgo_academic.ResourceManagementUnit', verbose_name='Program Study')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('submitted', 'submitted')], default='draft', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusgo_registrations.Program', verbose_name='Program Study')),
            ],
            options={
                'verbose_name': 'Matriculant',
                'verbose_name_plural': 'Matriculants',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=512, verbose_name='Name')),
                ('note', models.CharField(max_length=10000, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('program', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='campusgo_registrations.Program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
