# Generated by Django 2.2.10 on 2020-04-12 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campusgo_persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='person',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number'),
        ),
    ]
