# Generated by Django 2.2.10 on 2020-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusgo_persons', '0002_auto_20200412_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='person',
            name='fax',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='fax'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='whatsapp'),
        ),
        migrations.DeleteModel(
            name='PersonContact',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
