# Generated by Django 2.2.10 on 2020-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusgo_persons', '0003_auto_20200412_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaleducation',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'SD'), (1, 'SMP'), (2, 'SMA'), (3, 'D1'), (4, 'D2'), (5, 'D3'), (6, 'D4'), (7, 'S1'), (8, 'S2'), (9, 'S3')], default=7, verbose_name='level'),
        ),
    ]
