# Generated by Django 2.2.10 on 2020-02-27 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campusgo_persons', '0002_personsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campusgo_academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Personal',
                'verbose_name_plural': 'Teacher Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campusgo_persons.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Teacher ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('courses', models.ManyToManyField(to='campusgo_academic.Course', verbose_name='Courses')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campusgo_persons.Person', verbose_name='Person')),
                ('rmu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='campusgo_academic.ResourceManagementUnit', verbose_name='Homebase')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
