# Generated by Django 2.2.10 on 2020-04-12 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campusgo_academic', '0002_auto_20200412_1948'),
        ('campusgo_persons', '0005_auto_20200412_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'teacher personal',
                'verbose_name_plural': 'teacher personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campusgo_persons.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('tid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='teacher ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('courses', models.ManyToManyField(to='campusgo_academic.Course', verbose_name='courses')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campusgo_persons.Person', verbose_name='person')),
                ('rmu', models.ForeignKey(help_text='Teacher homebase.', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='campusgo_academic.ManagementUnit', verbose_name='management unit')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
    ]
