# Generated by Django 2.2.10 on 2020-02-27 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campusgo_rooms', '0001_initial'),
        ('campusgo_academic', '0001_initial'),
        ('campusgo_teachers', '0001_initial'),
        ('campusgo_lectures', '0002_auto_20200227_0839'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_assistant', to='campusgo_teachers.Teacher', verbose_name='Assistant'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusgo_academic.CurriculumCourse', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rmu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campusgo_academic.ResourceManagementUnit', verbose_name='Program Study'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campusgo_rooms.Room', verbose_name='Room Name'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_teacher', to='campusgo_teachers.Teacher', verbose_name='Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturestudent',
            unique_together={('lecture', 'student')},
        ),
    ]
