# Generated by Django 2.2.10 on 2020-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusgo_academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(choices=[(5, 'D3'), (7, 'S1'), (8, 'S2'), (9, 'S3')], default=7, verbose_name='level'),
        ),
    ]
